apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: cfs
  name: cfs
spec:
  replicas: 1
  selector:
    name: cfs
  template:
    metadata:
      labels:
        name: cfs
    spec:
      containers:
      - command:
        - /cfs
        resources:
          limits:
            cpu: 0.1
        image: yunxing/cfs:k8s
        name: cfs
        ports:
        - containerPort: 15524
          name: client
          protocol: TCP
        volumeMounts:
        - name: cfs-rootfs
          mountPath: /rootfs
          readOnly: true
        - name: cfs-var-run
          mountPath: /var/run
        - name: cfs-sys
          mountPath: /sys
          readOnly: true
        - name: cfs-var-lib-docker
          mountPath: /var/lib/docker
          readOnly: true
        - name: cfs-tmp
          mountPath: /tmp
        - name: cfs-data
          mountPath: /data
      volumes:
        - name: cfs-rootfs
          hostPath:
            path: /
        - name: cfs-var-run
          hostPath:
            path: /var/run
        - name: cfs-sys
          hostPath:
            path: /sys
        - name: cfs-var-lib-docker
          hostPath:
            path: /var/lib/docker
        - name: cfs-tmp
          hostPath:
            path: /tmp
        - name: cfs-data
          emptyDir: {}
